## Arrays

### Four Elements of Linear Algebra

#### Scalar  -  No Dimension Array
#### Vector  - 1 Dimension Array
#### Matrix  -  2 Dimension Array
#### Tensors - Collection of Matrixes



##  Numpy is the package to create Arrays

In [3]:
import numpy as np

In [111]:
L1 = [1,2,3,5]

In [44]:
## When creating to array from list type conversion occurs to ALL string if any element is string
## If any element is float and others int or boolean, conversion occurs to ALL float
## If any element is Boolean and others are integer, conversion occurs to ALL integer 

In [112]:
L2 = [9,11,13,20]

In [113]:
arr1 = np.array([L1,L2])

In [114]:
arr1

array([[ 1,  2,  3,  5],
       [ 9, 11, 13, 20]])

In [33]:
L*3

[1, 2, 3, 5, 'A', (9, 10), 1, 2, 3, 5, 'A', (9, 10), 1, 2, 3, 5, 'A', (9, 10)]

In [34]:
arr1*3

array([3, 6, 9, 15, 'AAA', (9, 10, 9, 10, 9, 10)], dtype=object)

### Slice an array and update element in parent or slice, then it reflects in both
### We need to make copy

In [12]:
arr1

array([1, 2, 3, 5])

In [13]:
arr2 = arr1[0:2]

In [14]:
arr2

array([1, 2])

In [15]:
arr2[0] = 20

In [16]:
arr1

array([20,  2,  3,  5])

In [19]:
arr1[1] = 60

In [20]:
arr2

array([20, 60])

In [21]:
arr1

array([20, 60, 60,  5])

In [22]:
arr3 = arr1.copy()

In [23]:
arr2[1] = 45

In [24]:
arr1

array([20, 45, 60,  5])

In [26]:
arr2

array([20, 45])

In [25]:
arr3

array([20, 60, 60,  5])

In [ ]:
## in arrays arange function is used to generate range of values

In [85]:
arr4 = np.arange(0,9)*3

In [86]:
arr4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [87]:
 ## (Rows, Columns) 'C or F' denotes how to populate elements C is for row wise and F for column 
## wise
np.reshape(arr4,(3,3),'C')

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [88]:
np.reshape(arr4,(3,3),'F')

array([[ 0,  9, 18],
       [ 3, 12, 21],
       [ 6, 15, 24]])